// Wig definitions with strategic boosts
const WIGS = {
  yellow: {
    id: 'yellow',
    name: 'The Classic',
    color: 0xf1c40f,
    healRate: 1.0,
    damageMult: 1.0,
    speedMult: 1.0,
    hungerMult: 1.0,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 1.0,
    desc: 'Healing only. Baseline.'
  },
  red: {
    id: 'red',
    name: 'The Firecracker',
    color: 0xe74c3c,
    healRate: 1.0,
    damageMult: 1.25,
    speedMult: 1.0,
    hungerMult: 1.0,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 1.0,
    desc: '+25% weapon damage'
  },
  blue: {
    id: 'blue',
    name: 'The Cool Breeze',
    color: 0x3498db,
    healRate: 1.0,
    damageMult: 1.0,
    speedMult: 1.22,
    hungerMult: 1.0,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 1.0,
    desc: '+Move speed'
  },
  green: {
    id: 'green',
    name: 'The Bushwhacker',
    color: 0x2ecc71,
    healRate: 1.0,
    damageMult: 1.0,
    speedMult: 1.0,
    hungerMult: 1.0,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 0.55,
    pirateAggroMult: 1.0,
    desc: 'Wildlife notice you slower'
  },
  purple: {
    id: 'purple',
    name: 'The Bouffant Royale',
    color: 0x9b59b6,
    healRate: 1.0,
    damageMult: 1.0,
    speedMult: 1.0,
    hungerMult: 0.65,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 1.0,
    desc: 'Hunger drains slower'
  },
  silver: {
    id: 'silver',
    name: 'The Steel Curl',
    color: 0xbdc3c7,
    healRate: 1.0,
    damageMult: 1.0,
    speedMult: 1.0,
    hungerMult: 1.0,
    damageTakenMult: 0.7,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 1.0,
    desc: 'Reduced damage taken'
  },
  pink: {
    id: 'pink',
    name: 'The Sweetheart',
    color: 0xff69b4,
    healRate: 1.55,
    damageMult: 1.0,
    speedMult: 1.0,
    hungerMult: 1.0,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 1.0,
    desc: 'Boosted healing rate'
  },
  orange: {
    id: 'orange',
    name: 'The Blaze',
    color: 0xe67e22,
    healRate: 1.0,
    damageMult: 1.0,
    speedMult: 1.0,
    hungerMult: 1.0,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.35,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 1.0,
    desc: 'Faster attack speed'
  },
  black: {
    id: 'black',
    name: 'The Shadow',
    color: 0x2c3e50,
    healRate: 1.0,
    damageMult: 1.0,
    speedMult: 1.0,
    hungerMult: 1.0,
    damageTakenMult: 1.0,
    attackSpeedMult: 1.0,
    wildlifeAggroMult: 1.0,
    pirateAggroMult: 0.55,
    desc: 'Pirates notice you slower'
  },
  rainbow: {
    id: 'rainbow',
    name: 'The Disco Bouffant',
    color: 0xffffff,
    healRate: 1.2,
    damageMult: 1.12,
    speedMult: 1.1,
    hungerMult: 0.85,
    damageTakenMult: 0.9,
    attackSpeedMult: 1.1,
    wildlifeAggroMult: 0.8,
    pirateAggroMult: 0.8,
    desc: 'Small bonus to everything'
  },
  golden: {
    id: 'golden',
    name: 'The Golden Bouffant',
    color: 0xffd700,
    healRate: 2.0,
    damageMult: 1.5,
    speedMult: 1.3,
    hungerMult: 0.5,
    damageTakenMult: 0.5,
    attackSpeedMult: 1.4,
    wildlifeAggroMult: 0.3,
    pirateAggroMult: 0.3,
    desc: 'THE ONE. You win.'
  }
};

const FOOD_TYPES = {
  candy: { name: 'Candy Bar', hunger: 45, fart: false, color: 0xf39c12, desc: 'Still sealed. A rare clean meal in this city.' },
  rotting: { name: 'Rotting Food', hunger: 18, fart: 'quiet', color: 0x27ae60, desc: 'Questionable at best. Keeps you walking.' },
  roadkill: { name: 'Roadkill', hunger: 32, fart: 'loud', color: 0x8B4513, desc: 'Fresh enough. The aftermath is... memorable.' }
};
